### ISSUE TITLE
Unable to run gactions in CLI

### ISSUE THREAD

**Issue by davidvc** [actions-on-google/gactions#1]
I have a script I try to run in CircleCI inside a Linux container. It fails saying "[ERROR] command requires authentication. try to run "gactions login" first".  When I run `gactions login --help` there are apparently no flags to login with a token.

So apparently I can't do automated deploys of my Google conversational actions, I have to deploy manually? I'm hoping very much you have a solution! I'm trying to set up a fully automated build/test/deploy pipeline.

Thanks!

David

Here's the script (`.circleci/deploy_preview.sh`)

```
#!/bin/bash

set -euxo pipefail

wget https://dl.google.com/gactions/v3/release/gactions-sdk_linux.tar.gz
tar xzvf gactions-sdk_linux.tar.gz

GACTIONS="./aog_cli/gactions"
chmod +x $GACTIONS

gactions login
$GACTIONS deploy preview
```

Here's the CircleCI config.yml file:

```
version: 2.1
orbs:
  node: circleci/node@3.0.0
executors:
  venus-executor:
    docker:
      - image: cimg/node:15.14.0
jobs:
  build:
    executor: venus-executor
    steps:
      - checkout
      - run:
          command: |
            cd functions
            npm install
  deploy-preview:
    executor: venus-executor
    steps:
      - checkout
      - run:
          command: |
            .circleci/deploy_preview.sh
workflows:
  version: 2
  merge:
    jobs:
      - build
      - deploy-preview:
          requires:
            - build
```
